config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.views.static import serve

# commenting out for testing engage without sso
# sso_client = Client(settings.SSO_SERVER, settings.SSO_PUBLIC_KEY, settings.SSO_PRIVATE_KEY)

urlpatterns = [
    path('', include('auth_app.urls', namespace='auth_app')),
    # Adding add engage URL's under app to differentiate between authentication and application urls
    path('app/', include('engage_app.urls', namespace='engage_app')),
    # Urls for the chat rooms, discussion boards and user messages
    path('chat/', include('communication_app.urls', namespace='communication_app')),

    # API STUFF
    path('api/', include(('api_app.urls', 'api_app'), namespace='api_app')),
    path('educate/api/', include(('educate_app.urls', 'educate_app'), namespace='educate_app')),

    # place it at whatever base url you like
    url(r'^select2/', include("django_select2.urls")),

    # For serving the static files from nginx
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }),
    
]

auth_app/models/faq.py
from django.db import models
from django.contrib.auth.models import User

from engage_app.utils.constants import FAQTypes


class FAQ(models.Model):
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField()
    faq_type = models.CharField(choices=FAQTypes.to_list(), max_length=50)
    viewed_users = models.ManyToManyField(User, related_name='viewed_faqs')
    liked_users = models.ManyToManyField(User, related_name='liked_faqs')

    def __str__(self):
        return self.title

base_app/models/base_option.py
from django.db import models

from base_app.models.base_engage_model import BaseEngageModel


class BaseOption(BaseEngageModel):
    class Meta:
        abstract = True

    title = models.CharField(max_length=200)
    mapping = models.CharField(null=True, blank=True, max_length=200)
    order_number = models.SmallIntegerField()

    def to_json(self):
        return dict(
            id=str(self.id),
            title=self.title,
            mapping=self.mapping
        )

base_app/models/base_section.py
from django.db import models

from base_app.models.base_engage_model import BaseEngageModel


class BaseSection(BaseEngageModel):
    class Meta:
        abstract = True

    name = models.CharField(max_length=200)
    description = models.TextField()
    order_number = models.SmallIntegerField()
    is_valid_researcher = models.BooleanField()
    is_valid_patient = models.BooleanField()
    is_valid_family_of_patient = models.BooleanField()
    is_valid_caretaker_of_patient = models.BooleanField()
    is_valid_passive = models.BooleanField()
    is_published = models.BooleanField(default=False)

    def to_json(self):
        return {
            'name': self.name,
            'description': self.description,
            'order_number': self.order_number,
            'is_valid_researcher': self.is_valid_researcher,
            'is_valid_patient': self.is_valid_patient,
            'is_valid_family_of_patient': self.is_valid_family_of_patient,
            'is_valid_caretaker_of_patient': self.is_valid_caretaker_of_patient,
            'is_valid_passive': self.is_valid_passive,
            'is_published': self.is_published,
            'id': str(self.id)
        }

    def __str__(self):
        return f'{self.name} - {self.order_number}'

auth_app/forms/authentication.py
import string
from django import forms

from django.contrib.auth.password_validation import validate_password


class AuthenticationForm(forms.Form):

    def to_json(self):
        if self.is_valid():
            return self.cleaned_data
        else:
            return dict(error="This Form did not contain valid input")


class CustomPasswordResetConfirmForm(forms.Form):

    encoded_user_id = forms.CharField(label='encoded_user_id')
    token = forms.CharField(label='user_token')
    new_password1 = forms.CharField(label="new_password1", validators=[validate_password])
    new_password2 = forms.CharField(label="new_password1")

    def __init__(self, *args, **kwargs):
        super(CustomPasswordResetConfirmForm, self).__init__(*args, **kwargs)
        self.fields['encoded_user_id'].required = True
        self.fields['token'].required = True
        self.fields['new_password1'].required = True
        self.fields['new_password2'].required = True

    def clean(self):
        cleaned_data = super(CustomPasswordResetConfirmForm, self).clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")

        if new_password1 and new_password2 and new_password1 != new_password2:
            self._errors['new_password2'] = self.error_class(["The two password fields didn’t match."])

        return cleaned_data

auth_app/forms/contact_log.py
from django import forms
from auth_app.models import ContactLog


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactLog
        fields = '__all__'

auth_app/forms/user_profile_question_admin.py
from django import forms
from django.contrib import admin
from auth_app.models import UserProfileQuestion


class UserProfileQuestionForm(forms.ModelForm):
    class Meta:
        model = UserProfileQuestion
        fields = [
            'parent_question', 'section', 'order_number', 'type', 'is_required_researcher', 'is_required_patient',
            'is_required_family_of_patient', 'is_required_passive', 'text_for_researcher', 'text_for_patient',
            'text_for_family_of_patient', 'text_for_caretaker_of_patient', 'text_for_passive', 'help_text', 'dev_code'
        ]

auth_app/forms/user_profile_section_admin.py
from django import forms
from django.contrib import admin
from auth_app.models import UserProfileSection


class UserProfileSectionForm(forms.ModelForm):
    class Meta:
        model = UserProfileSection
        fields = [
            'name', 'description', 'is_valid_researcher', 'is_valid_patient', 'is_valid_family_of_patient',
            'is_valid_passive', 'is_valid_caretaker_of_patient', 'is_published', 'order_number'
        ]
        widgets = {
            'description': forms.Textarea(attrs={'rows': 6})
        }

communication_app/forms/discussion_board.py
from django import forms
from communication_app.models import DiscussionBoard


class DiscussionBoardForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_task_id = kwargs.pop('parent_task_id', None)
        self.board_creator_id = kwargs.pop('board_creator_id', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = DiscussionBoard
        fields = ['title', 'description']
        widgets = {
            'title': forms.TextInput()
        }

    def save(self, commit=False):
        # Save the discussion board if and only if the parent task id and the board creator id were supplied
        # otherwise we cannot create the discussion board
        discussion_board = super().save(commit=commit)
        if self.parent_task_id and self.board_creator_id:
            discussion_board.parent_task_id = self.parent_task_id
            discussion_board.board_creator_id = self.board_creator_id
            discussion_board.save()
        return discussion_board

api_app/controllers/community.py
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from api_app.serializers import CommunityListSerializer
from api_app.serializers.user_profile import UserProfileQuestionSerializer
from auth_app.models import UserProfile, UserProfileQuestion, UserProfileAnswer, ResearchInterest
from engage_app.utils import UserRoles, QuestionTypes
from datetime import datetime

DATE_QUESTION_TYPES = [
    QuestionTypes.DATE_PICKER.name,
    QuestionTypes.DATE_PICKER_YEAR.name
]


class CommunityListController(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        validated_user_filter_list = []
        user_supplied_filters = False
        if "filters" in request.data and len(request.data['filters']) > 0:
            # First get the filter list from the request and reduce it down to a list of ids
            filter_dict = request.data['filters']
            user_supplied_filters = True
            filter_id_list = list(filter_dict.keys())

            # Now with the list of ids, we can search for users that have given an answer to this question
            answers_query = UserProfileAnswer.objects.filter(question_id__in=filter_id_list)
            unique_user_id_list = list(set(answers_query.values_list("user_profile__user_id", flat=True)))
            validated_user_filter_list = unique_user_id_list.copy()

            # EDI Filter
            excluded_users_for_edi_filter = []
            for answer in answers_query:
                # If the question is an EDI question, check if the user has set their EDI answers to public
                # Don't add the user to the excluded list if they are already in the list
                if answer.question.dev_code.startswith("E") and (
                        answer.user_profile.user_id not in excluded_users_for_edi_filter
                ):
                    try:
                        show_edi_public = UserProfileAnswer.objects.get(
                            user_profile_id=answer.user_profile.user_id, question__dev_code="E-SETTING"
                        ).selected_options[0] == "True"
                    except UserProfileAnswer.DoesNotExist:
                        # If the user has not set their EDI setting, then we can assume they have not set their EDI answers to public
                        show_edi_public = False
                    if not show_edi_public:
                        excluded_users_for_edi_filter.append(answer.user_profile.user_id)
            # Remove the users who have set their EDI answers to non-public from validated_user_filter_list
            for user in excluded_users_for_edi_filter:
                validated_user_filter_list.remove(user)

            # For each user found in the user answers above, query the returned answers for their answers and if the
            # user has a match for that question we will add them to the valid id list, but if they don't have a match
            # for a question then we will remove them from the list and continue iterating over the user list
            for user in unique_user_id_list:
                # check if the user was removed from the validated user list, then we can skip them
                if user not in validated_user_filter_list:
                    continue

                # Query all the answers for this user, check if the answers query exists after limiting to this user
                # and check if the number of questions found matches the number of questions given by the user
                # performing the search
                user_answer_query = answers_query.filter(user_profile__user_id=user)
                if not answers_query.exists() or answers_query.count() < len(filter_id_list):
                    validated_user_filter_list.remove(user)
                    continue
                for user_answer in user_answer_query:
                    if user not in validated_user_filter_list:
                        continue

                    # Convert the selected options to a list and filter out any empty list values from the users
                    # selected answers
                    selected_options = list(
                        filter(lambda search: search != '', filter_dict[str(user_answer.question_id)])
                    )
                    users_selected_options = list(user_answer.selected_options)

                    # if the selected options from the user is a string, convert to a list
                    if type(selected_options) == str:
                        selected_options = [selected_options]
                    # Now based on the question type, modify the user profile answers to get the correct answers
                    if user_answer.question.type in DATE_QUESTION_TYPES and len(selected_options) == 2:
                        # Convert the users answers and the search dates from the range picker into date time
                        # objects using the year, month and day from the string or just the year based on the question
                        # type. Which is if we are using the year (4 characters) or full date (10 characters)
                        if user_answer.question.type == QuestionTypes.DATE_PICKER_YEAR.name:
                            user_time_index = 4
                            date_format = "%Y"
                        else:
                            user_time_index = 10
                            date_format = "%Y-%m-%d"

                        users_date_list = [
                            datetime.strptime(user_date[0:user_time_index], date_format) for user_date in
                            users_selected_options
                        ]
                        search_date_list = [
                            datetime.strptime(search_date, date_format) for search_date in selected_options
                        ]

                        # Now check if the user date is in-between the first and the second date in the search date list
                        if not (search_date_list[0] <= users_date_list[0] <= search_date_list[1]):
                            validated_user_filter_list.remove(user)

                        # Since the users date either passes or fails the check at this point, they can stay in the list
                        # and we can go to the next check or they get removed and we go to the next user
                        continue

                    # If the user question is a research interest, we need to need to map the values
                    # to the proper terms not ids
                    if user_answer.question.linked_to_research_interest:
                        users_selected_options = [
                            ResearchInterest.objects.get(id=interest).title for interest in users_selected_options
                        ]

                    if not any(selection in users_selected_options for selection in selected_options):
                        validated_user_filter_list.remove(user)
                        continue

        # get a reference to the current user profile to perform the checks below
        current_user_profile = UserProfile.objects.get(user=request.user)

        # Build the patient list if the user is an active researcher or patient partner
        community_list = []
        anon_count_patient = 0
        # TODO: We can probably optimize this block
        if current_user_profile.is_approved_researcher or current_user_profile.is_patient_partner:
            patient_list = UserProfile.objects.filter(role__in=UserRoles.get_patient_partner_types())
            # get the anon user count
            anon_count_patient=patient_list.filter(is_anonymous=True).count()
            # once we have the anon count update the patient list to exclude anon profiles
            patient_list = patient_list.filter(is_anonymous=False)
            if user_supplied_filters:
                patient_list = patient_list.filter(user_id__in=validated_user_filter_list)
            community_list = [patient.to_public_json() for patient in patient_list]

        # Now add on all the data for the approved researchers
        researcher_list = UserProfile.objects.filter(
            role__in=UserRoles.get_research_partner_types(), is_active_researcher=True
        ).exclude(user__username="admin")
        # get the researcher anon count
        anon_count_researcher=researcher_list.filter(is_anonymous=True).count()
        # once we have the count exclude anon users
        researcher_list = researcher_list.filter(is_anonymous=False)
        if user_supplied_filters:
            researcher_list = researcher_list.filter(user_id__in=validated_user_filter_list)

        # only send the anonymous user when we are not filtering
        # filter out the anon users
        if not user_supplied_filters:
            for _ in range(anon_count_patient+anon_count_researcher):
                new_anonymous_obj = {'is_anonymous': True}
                community_list.append(new_anonymous_obj)
        community_list = [*community_list, *[researcher.to_public_json() for researcher in researcher_list]]
        # serialize the data to return only the fields required for the community list and return the response as json
        serialized_data = CommunityListSerializer(community_list, many=True)
        return Response(data=serialized_data.data, content_type="application/json", status=status.HTTP_200_OK)


class CommunityListFiltersController(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        # First build a list of all the searchable user profile questions with their question ids, labels and
        # convert it to a json response before returning it to the user, this way they can build all the filters
        # for dynamic fields
        searchable_questions = UserProfileQuestion.objects.filter(

templates/administration/forms/user_profile_question.html
<form method="POST" id="user-profile-question-form"
      action="{% url "auth_app:admin" %}"
      class="user-profile-form" data-instance-id="" data-form-type="QUESTION"
>
    {% csrf_token %}
    {# TODO: Add switch to show and hide required fields #}
    <div class="form-group row">
        {{ profile_question_form.is_required_patient }}
        <label for="id_is_required_patient">{{ profile_question_form.is_required_patient.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_question_form.is_required_researcher }}
        <label for="id_is_required_researcher">{{ profile_question_form.is_required_researcher.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_question_form.is_required_family_of_patient }}
        <label for="id_is_required_family_of_patient">{{ profile_question_form.is_required_family_of_patient.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_question_form.is_required_passive }}
        <label for="id_is_required_passive">{{ profile_question_form.is_required_passive.label }}</label>
    </div>
    {# TODO: Add switch to show and hide text for fields #}
    <div class="form-group column">
        <label for="id_text_for_patient">{{ profile_question_form.text_for_patient.label }}</label>
        {{ profile_question_form.text_for_patient }}
    </div>
    <div class="form-group column">
        <label for="id_text_for_researcher">{{ profile_question_form.text_for_researcher.label }}</label>
        {{ profile_question_form.text_for_researcher }}
    </div>
    <div class="form-group column">
        <label for="id_text_for_family_of_patient">{{ profile_question_form.text_for_family_of_patient.label }}</label>
        {{ profile_question_form.text_for_family_of_patient }}
    </div>
    <div class="form-group column">
        <label for="id_text_for_caretaker_of_patient">{{ profile_question_form.text_for_caretaker_of_patient.label }}</label>
        {{ profile_question_form.text_for_caretaker_of_patient }}
    </div>
    <div class="form-group column">
        <label for="id_text_for_passive">{{ profile_question_form.text_for_passive.label }}</label>
        {{ profile_question_form.text_for_passive }}
    </div>

    <div class="form-group column">
        <label for="id_order_number">{{ profile_question_form.order_number.label }}</label>
        {{ profile_question_form.order_number }}
    </div>

    <div class="form-group column">
        <label for="id_section">{{ profile_question_form.section.label }}</label>
        {{ profile_question_form.section }}
    </div>

    <div class="form-group column">
        <label for="id_type">{{ profile_question_form.type.label }}</label>
        {{ profile_question_form.type }}
    </div>
    <div class="form-group column hidden">
        <label for="id_options_list">
            Options List <small><em>(separate each option with a semicolon ';')</em></small>
        </label>
        <textarea id="id_options_list" rows="4"></textarea>
    </div>
    <div class="form-group column">
        <label for="id_dev_code">{{ profile_question_form.dev_code.label }}</label>
        {{ profile_question_form.dev_code }}
    </div>

    {# TODO: Add question option form #}
    <div class="button-container">
        <button type="button">Cancel</button>
        <button type="submit">Submit</button>
    </div>
</form>

templates/administration/forms/user_profile_section.html
<form method="POST" id="user-profile-section-form"
      action="{% url "auth_app:admin" %}"
      class="user-profile-form" data-instance-id="" data-form-type="SECTION"
>
    {% csrf_token %}
    <div class="form-group column">
        <label for="id_name">{{ profile_section_form.name.label }}</label>
        {{ profile_section_form.name }}
    </div>
    <div class="form-group column">
        <label for="id_order_number">{{ profile_section_form.order_number.label }}</label>
        {{ profile_section_form.order_number }}
    </div>
    <div class="form-group row">
        {{ profile_section_form.is_valid_patient }}
        <label for="id_is_valid_patient">{{ profile_section_form.is_valid_patient.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_section_form.is_valid_researcher }}
        <label for="id_is_valid_researcher">{{ profile_section_form.is_valid_researcher.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_section_form.is_valid_family_of_patient }}
        <label for="id_is_valid_family_of_patient">{{ profile_section_form.is_valid_family_of_patient.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_section_form.is_valid_caretaker_of_patient }}
        <label for="id_is_valid_caretaker_of_patient">{{ profile_section_form.is_valid_caretaker_of_patient.label }}</label>
    </div>
    <div class="form-group row">
        {{ profile_section_form.is_valid_passive }}
        <label for="id_is_valid_passive">{{ profile_section_form.is_valid_passive.label }}</label>
    </div>
    <div class="form-group column">
        <label for="id_description">{{ profile_section_form.description.label }}</label>
        {{ profile_section_form.description }}
    </div>
    <div class="button-container">
        <button type="button">Cancel</button>
        <button type="submit">Submit</button>
    </div>
</form>